#URL=<loaded from secreted vault>
#ELASTIC_API_KEY=<loaded from secreted vault>
request_timeout=60
retry_on_timeout=True
max_retries=3
http_compress=True
# Connection pooling for cloud
connections_per_node=10